package org.vrex.cacheMeOutside.service;

import jakarta.transaction.Transactional;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import org.vrex.cacheMeOutside.dto.NewAppRequest;
import org.vrex.cacheMeOutside.entity.mysql.Application;
import org.vrex.cacheMeOutside.recognito.Client;
import org.vrex.cacheMeOutside.repository.ApplicationRepository;
import org.vrex.cacheMeOutside.utility.ApplicationException;

@Service
@Slf4j
public class ApplicationService {

    private final String LOG_TEXT = "APP_MODULE : ";
    private final String ERROR_TEXT = "APP_MODULE_ERROR : ";

    @Autowired
    private ApplicationRepository applicationRepository;

    @Autowired
    private Client recognitoClient;

    @Transactional
    public Application addApplication(NewAppRequest request) {
        String appName = request.getName();
        log.info("{} Attempting to save new application : {}", LOG_TEXT, appName);
        Application application = null;
        try {
            application = applicationRepository.saveAndFlush(new Application(request));
            log.info("{} Saved new application {} with ID : {}", LOG_TEXT, appName, application.getId());
            /**
             * Add call to recognito to save application
             * Change return type to also include root user being generated by Recognito
             */
        } catch (Exception exception) {
            log.error("{} Attempting to save application {} -> {}", ERROR_TEXT, appName, exception);
            throw ApplicationException.builder().
                    errorMessage(exception.getMessage()).
                    status(HttpStatus.INTERNAL_SERVER_ERROR).
                    build();
        }
        return application;
    }
}
